
(* Direction declarations *)

direction-decl  = {word}, present-being, indefinite, "direction", ["," opposite-decl] ".";
opposite-decl   = definite, "opposite", present-being, {word};

(* Things *)

sentence        = (there-decl | be-decl | ability-decl | entity-decl), ".";

entity-decl     = (there-decl | be-decl) [":", quoted-string];

there-decl      = "there", present-being, object, [location-spec] ;
be-decl         = subject, present-being, [object], [locations];

locations       = location-spec, {",", location-spec};
location-spec   = location-name, {preposition}, entity-reference;

ability-decl    = passive-ability | active-ability;
passive-ability = subject, "can", "be", past-participle, {",", past-participle};
active-ability  = "you", "can", infinitive, subject, {",", infinitive, subject};

(* common patterns *)

object          = [article], {word};
subject         = subjective-pronoun | noun;
noun            = [article], {word}; 

present-being   = "is" | "are";
article         = "a" | "an" | "the" | integer;
quoted-string   = '"', {character} , '"';

comment         = "(", {character}, ")";

