
(* Direction declarations *)

direction-decl  = {word}, present-being, indefinite, "direction", ["," opposite-decl] ".";
opposite-decl   = definite, "opposite", present-being, {word};

(* Things *)

sentence        = (there-sentence | you-can-sentence | active-sentence | description), ".";

active-sentence = subject, (be-sentence | can-sentence);

there-sentence  = "there", present-being, noun, container-rel ;
be-sentence     = present-being, ( property | be-spec ) ;

(* TODO: add support for saying what a thing is. Not needed while just rooms + things *)
be-spec         = [article {word}], (directions | container-rel);
property        = "locked"; (* specify better *)

directions      = direction-rel , {",", direction-rel};
direction-rel   = location-name, {preposition}, entity-reference;

container-rel   = ("in" | "on") noun;

can-sentence    = "can", "be", past-participle, {",", past-participle};
you-can-sentence= "you", "can", infinitive, subject, {",", infinitive, subject};

(* common patterns *)

description     = quoted-string;

object          = [article], {word};
subject         = subjective-pronoun | noun;
noun            = [article], {word}; 

present-being   = "is" | "are";
article         = "a" | "an" | "the" | integer;
quoted-string   = '"', {character} , '"';

comment         = "(", {character}, ")";

