asset-file:         asset-desc (objects-desc)? (rooms-desc)?

asset-desc:         descriptive be (article?) name period (detailed-desc)?

objects-desc:       "objects" ":" objects-list
objects-list:       "-" object-desc (detailed-desc)? (object-abilities)?
object-desc:        article noun (separator adjective)* "."
object-interaction: "you" "can" verb reference (separator verb reference)* "."

rooms-desc:         "rooms" ":" rooms-list
rooms-list:         "-" room-desc (locked-details)?
locked-details:     "you" "need" # TODO: problem here maybe? referential integrity needed anyway


detailed-desc:      descriptive quoted-string "."
quoted-string       quote (.)* quote
reference:          ("it" | "them")
descriptive:        ("it" "is" | "they" "are")
separator:          ("," | "&")
noun:               word ((whitespace | "-" | "'") word)*
article             "a" | "an" | "some" | "the" | integer
