// generated by gen_code.py
#pragma once
OPCODE(halt      , 0x00,  +0,  +0) // halts the virtual machine
OPCODE(loadci    , 0x01,  +4,  +4) // pushes a constant on the stack from a direct value in the code
OPCODE(loadcm    , 0x02,  +4,  +4) // pushes a constant on the stack from a value from the pool
OPCODE(loadg     , 0x03,  +4,  +4) // pushes a global on the stack
OPCODE(loadl     , 0x04,  +1,  +4) // pushes a local variable onto the stack
OPCODE(loada     , 0x05,  +0,  -4) // pops an array reference and index, and pushes the array item
OPCODE(storeg    , 0x06,  +4,  -4) // pops a value from the stack into a global
OPCODE(storel    , 0x07,  +1,  -4) // pops a value from the stack into a local
OPCODE(storea    , 0x08,  +0, -12) // pops a value into an array slot
OPCODE(drop      , 0x09,  +0,  -4) // removes the top-of-stack.
OPCODE(dup       , 0x0a,  +0,  +4) // duplicates the item on TOS.
OPCODE(amake     , 0x0b,  +4,  +4) // creates an array and pushes a reference to it
OPCODE(adel      , 0x0c,  +0,  -4) // deletes an array pointed to by the TOS
OPCODE(cclone    , 0x0d,  +0,  +4) // creates a copy of a constant pool object on TOS
OPCODE(mclone    , 0x0e,  +0,  +4) // creates a copy of a dynamic memory object on TOS
OPCODE(cmake     , 0x0f,  +0,  +0) // creates an instance of a constant pool prototype on TOS
OPCODE(mmake     , 0x10,  +0,  +0) // creates an instance of a dynamic memory prototype on TOS
OPCODE(del       , 0x11,  +0,  -4) // frees the memory used by an object on TOS
OPCODE(iowrite   , 0x12,  +0,  -4) // writes the top of stack to the IO device
OPCODE(ioread    , 0x13,  +0,  +4) // reads a line of text from the IO device onto the stack
OPCODE(iostyle   , 0x14,  +2,  +0) // sets the IO device style
OPCODE(i2s       , 0x15,  +0,  +0) // converts the TOS from integer to string
OPCODE(i2f       , 0x16,  +0,  +0)
OPCODE(f2s       , 0x17,  +0,  +0)
OPCODE(f2i       , 0x18,  +0,  +0)
OPCODE(p2s       , 0x19,  +0,  +0) // converts the TOS from property reference to string
OPCODE(addi      , 0x1a,  +0,  -4) // adds two integers
OPCODE(subi      , 0x1b,  +0,  -4) // subtracts an integer from another
OPCODE(muli      , 0x1c,  +0,  -4) // multiplies two integers
OPCODE(divi      , 0x1d,  +0,  -4) // divides an integer by another
OPCODE(addf      , 0x1e,  +0,  -4) // adds two floats
OPCODE(subf      , 0x1f,  +0,  -4) // subtracts an float from another
OPCODE(mulf      , 0x20,  +0,  -4) // multiplies two floats
OPCODE(divf      , 0x21,  +0,  -4) // divides an float by another

