
include-decl    = "use", {word}, ".";
sentence        = (there-sentence| active-sentence | description | synonym-decl), ".";

(* Synonyms *)

synonym-decl    = you-synonym | means-synonym;
you-synonym     = "you", "can", "say", noun, "instead", "of", noun;
means-synonym   = noun, "means", noun;

(* Things *)

active-sentence = subject, (be-sentence | can-sentence);

there-sentence  = "there", present-being, noun, container-rel ;
be-sentence     = present-being, ( property | be-spec ) ;

(* TODO: add support for saying what a thing is. Not needed while just rooms + things *)
be-spec         = subject, "is", (direction-decl) | ( [kind] (directions | container-rel));
property        = "locked"; (* specify better *)

direction-decl  = indefinite, "direction", ["," opposite-decl];
opposite-decl   = definite, "opposite", present-being, {word};
directions      = direction-rel , {",", direction-rel};
direction-rel   = location-name, {preposition}, entity-reference;

container-rel   = ("in" | "on") noun;

can-sentence    = "can", "be", past-participle, {",", past-participle};
(* you-can-sentence= "you", "can", infinitive, subject, {",", infinitive, subject}; *)

(* common patterns *)

description     = quoted-string;

kind            = [article], {word};
object          = [article], {word};
subject         = subjective-pronoun | noun;
noun            = [article], {word}; 

present-being   = "is" | "are";
article         = "a" | "an" | "the" | "some" | integer;
quoted-string   = '"', {character} , '"';

comment         = "(", {character}, ")";

